// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingApp.Core.Entities;
using TrainingApp.Infrastructure.Data;

#nullable disable

namespace TrainingApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TrainingAppDbContext))]
    [Migration("20260207214731_AddFatLossModule")]
    partial class AddFatLossModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("p_k_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("p_k_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("p_k_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.AdaptationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("input_summary");

                    b.Property<string>("OutputSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("output_summary");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<bool>("WasApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("was_applied");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.Property<Guid?>("WorkoutSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_set_id");

                    b.HasKey("Id")
                        .HasName("p_k_adaptation_logs");

                    b.HasIndex("WorkoutSetId")
                        .HasDatabaseName("i_x_adaptation_logs_workout_set_id");

                    b.HasIndex("WorkoutId", "CreatedAt")
                        .HasDatabaseName("i_x_adaptation_logs_workout_id_created_at");

                    b.ToTable("adaptation_logs");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.DailyMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Atl")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("atl");

                    b.Property<decimal?>("AverageSessionRpe")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("average_session_rpe");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Ctl")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ctl");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("ReadinessScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("readiness_score");

                    b.Property<int>("TotalReps")
                        .HasColumnType("integer")
                        .HasColumnName("total_reps");

                    b.Property<int>("TotalSets")
                        .HasColumnType("integer")
                        .HasColumnName("total_sets");

                    b.Property<decimal>("TotalVolume")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_volume");

                    b.Property<decimal>("Trimp")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("trimp");

                    b.Property<decimal>("Tsb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tsb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkoutCount")
                        .HasColumnType("integer")
                        .HasColumnName("workout_count");

                    b.HasKey("Id")
                        .HasName("p_k_daily_metrics");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("i_x_daily_metrics_user_id_date");

                    b.ToTable("daily_metrics");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.DeficitPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CurrentAdaptationPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("current_adaptation_percent");

                    b.Property<int?>("DietBreakIntervalWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("diet_break_interval_weeks");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly?>("LastDietBreakDate")
                        .HasColumnType("date")
                        .HasColumnName("last_diet_break_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<decimal>("StartWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("start_weight_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("target_weight_kg");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeeklyRateKg")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("weekly_rate_kg");

                    b.HasKey("Id")
                        .HasName("p_k_deficit_phases");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("i_x_deficit_phases_user_id_status");

                    b.ToTable("deficit_phases");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("equipment");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_custom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string>("PrimaryMuscles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("primary_muscles");

                    b.PrimitiveCollection<string>("SecondaryMuscles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("secondary_muscles");

                    b.Property<int?>("WgerId")
                        .HasColumnType("integer")
                        .HasColumnName("wger_id");

                    b.HasKey("Id")
                        .HasName("p_k_exercises");

                    b.HasIndex("Category")
                        .HasDatabaseName("i_x_exercises_category");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_exercises_name");

                    b.HasIndex("WgerId")
                        .IsUnique()
                        .HasDatabaseName("i_x_exercises_wger_id")
                        .HasFilter("wger_id IS NOT NULL");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.MuscleVolumeTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MaxSetsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("max_sets_per_week");

                    b.Property<int>("MinSetsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("min_sets_per_week");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("muscle_group");

                    b.Property<Guid>("ProgramPhaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_phase_id");

                    b.Property<int>("TargetSetsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("target_sets_per_week");

                    b.HasKey("Id")
                        .HasName("p_k_muscle_volume_targets");

                    b.HasIndex("ProgramPhaseId", "MuscleGroup")
                        .IsUnique()
                        .HasDatabaseName("i_x_muscle_volume_targets_program_phase_id_muscle_group");

                    b.ToTable("muscle_volume_targets");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.NeatLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CompensationPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("compensation_percent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("EstimatedNeatKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("estimated_neat_kcal");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("StepCount")
                        .HasColumnType("integer")
                        .HasColumnName("step_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_neat_logs");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("i_x_neat_logs_user_id_date");

                    b.ToTable("neat_logs");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("duration_weeks");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("template");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_programs");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("i_x_programs_user_id_status");

                    b.HasIndex("UserId", "Template")
                        .HasDatabaseName("i_x_programs_user_id_template");

                    b.ToTable("programs");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.ProgramExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<decimal?>("IntensityPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("intensity_percentage");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProgramWorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_workout_id");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<string>("SupersetGroup")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("superset_group");

                    b.Property<int>("TargetRepsMax")
                        .HasColumnType("integer")
                        .HasColumnName("target_reps_max");

                    b.Property<int>("TargetRepsMin")
                        .HasColumnType("integer")
                        .HasColumnName("target_reps_min");

                    b.Property<decimal?>("TargetRpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("target_rpe");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer")
                        .HasColumnName("target_sets");

                    b.HasKey("Id")
                        .HasName("p_k_program_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("i_x_program_exercises_exercise_id");

                    b.HasIndex("ProgramWorkoutId", "OrderIndex")
                        .HasDatabaseName("i_x_program_exercises_program_workout_id_order_index");

                    b.ToTable("program_exercises");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.ProgramPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("duration_weeks");

                    b.Property<decimal>("IntensityMultiplier")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("intensity_multiplier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<int>("TargetRir")
                        .HasColumnType("integer")
                        .HasColumnName("target_rir");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<decimal>("VolumeMultiplier")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("volume_multiplier");

                    b.HasKey("Id")
                        .HasName("p_k_program_phases");

                    b.HasIndex("ProgramId", "OrderIndex")
                        .HasDatabaseName("i_x_program_phases_program_id_order_index");

                    b.ToTable("program_phases");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.ProgramWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("focus");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProgramPhaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_phase_id");

                    b.HasKey("Id")
                        .HasName("p_k_program_workouts");

                    b.HasIndex("ProgramPhaseId", "OrderIndex")
                        .HasDatabaseName("i_x_program_workouts_program_phase_id_order_index");

                    b.ToTable("program_workouts");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.RecoveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("EnergyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("energy_level");

                    b.Property<int?>("Mood")
                        .HasColumnType("integer")
                        .HasColumnName("mood");

                    b.Property<int?>("MuscleReadiness")
                        .HasColumnType("integer")
                        .HasColumnName("muscle_readiness");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("SleepHours")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("sleep_hours");

                    b.Property<int?>("SleepQuality")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_quality");

                    b.Property<int?>("StressLevel")
                        .HasColumnType("integer")
                        .HasColumnName("stress_level");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_recovery_logs");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("i_x_recovery_logs_user_id_date");

                    b.ToTable("recovery_logs");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<UserSettings>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("MovingAverage30d")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("moving_average30d");

                    b.Property<decimal?>("MovingAverage7d")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("moving_average7d");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WeeklyRateKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weekly_rate_kg");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("p_k_weight_logs");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("i_x_weight_logs_user_id_date");

                    b.ToTable("weight_logs");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int?>("PostWorkoutFatigue")
                        .HasColumnType("integer")
                        .HasColumnName("post_workout_fatigue");

                    b.Property<int?>("PreWorkoutReadiness")
                        .HasColumnType("integer")
                        .HasColumnName("pre_workout_readiness");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<int?>("SessionRpe")
                        .HasColumnType("integer")
                        .HasColumnName("session_rpe");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_workouts");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("i_x_workouts_program_id")
                        .HasFilter("program_id IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_workouts_status");

                    b.HasIndex("UserId", "ScheduledAt")
                        .HasDatabaseName("i_x_workouts_user_id_scheduled_at");

                    b.ToTable("workouts");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActualReps")
                        .HasColumnType("integer")
                        .HasColumnName("actual_reps");

                    b.Property<decimal?>("ActualWeight")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("actual_weight");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("adjustment_reason");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsWarmup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_warmup");

                    b.Property<DateTimeOffset?>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int?>("Rir")
                        .HasColumnType("integer")
                        .HasColumnName("rir");

                    b.Property<decimal?>("Rpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rpe");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<int?>("TargetReps")
                        .HasColumnType("integer")
                        .HasColumnName("target_reps");

                    b.Property<int?>("TargetRir")
                        .HasColumnType("integer")
                        .HasColumnName("target_rir");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("target_weight");

                    b.Property<bool>("WasAutoAdjusted")
                        .HasColumnType("boolean")
                        .HasColumnName("was_auto_adjusted");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("p_k_workout_sets");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("i_x_workout_sets_exercise_id");

                    b.HasIndex("WorkoutId", "SetNumber")
                        .HasDatabaseName("i_x_workout_sets_workout_id_set_number");

                    b.ToTable("workout_sets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_claims__asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_logins__asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("TrainingApp.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles__asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_tokens__asp_net_users_user_id");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.AdaptationLog", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_adaptation_logs__workouts_workout_id");

                    b.HasOne("TrainingApp.Core.Entities.WorkoutSet", "WorkoutSet")
                        .WithMany()
                        .HasForeignKey("WorkoutSetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_adaptation_logs__workout_sets_workout_set_id");

                    b.Navigation("Workout");

                    b.Navigation("WorkoutSet");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.DailyMetrics", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", "User")
                        .WithMany("DailyMetrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_daily_metrics__asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.DeficitPhase", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", "User")
                        .WithMany("DeficitPhases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_deficit_phases__asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.MuscleVolumeTarget", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.ProgramPhase", "ProgramPhase")
                        .WithMany("VolumeTargets")
                        .HasForeignKey("ProgramPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_muscle_volume_targets__program_phases_program_phase_id");

                    b.Navigation("ProgramPhase");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.NeatLog", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", "User")
                        .WithMany("NeatLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_neat_logs__asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.Program", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", "User")
                        .WithMany("Programs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_programs__asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.ProgramExercise", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.Exercise", "Exercise")
                        .WithMany("ProgramExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_program_exercises_exercises_exercise_id");

                    b.HasOne("TrainingApp.Core.Entities.ProgramWorkout", "ProgramWorkout")
                        .WithMany("Exercises")
                        .HasForeignKey("ProgramWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_program_exercises__program_workouts_program_workout_id");

                    b.Navigation("Exercise");

                    b.Navigation("ProgramWorkout");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.ProgramPhase", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.Program", "Program")
                        .WithMany("Phases")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_program_phases_programs_program_id");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.ProgramWorkout", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.ProgramPhase", "ProgramPhase")
                        .WithMany("Workouts")
                        .HasForeignKey("ProgramPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_program_workouts_program_phases_program_phase_id");

                    b.Navigation("ProgramPhase");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.RecoveryLog", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", "User")
                        .WithMany("RecoveryLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_recovery_logs__asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.WeightLog", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weight_logs_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.Workout", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.Program", "Program")
                        .WithMany("Workouts")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_workouts_programs_program_id");

                    b.HasOne("TrainingApp.Core.Entities.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_workouts_asp_net_users_user_id");

                    b.Navigation("Program");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.WorkoutSet", b =>
                {
                    b.HasOne("TrainingApp.Core.Entities.Exercise", "Exercise")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_workout_sets_exercises_exercise_id");

                    b.HasOne("TrainingApp.Core.Entities.Workout", "Workout")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_workout_sets_workouts_workout_id");

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.Exercise", b =>
                {
                    b.Navigation("ProgramExercises");

                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.Program", b =>
                {
                    b.Navigation("Phases");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.ProgramPhase", b =>
                {
                    b.Navigation("VolumeTargets");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.ProgramWorkout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.User", b =>
                {
                    b.Navigation("DailyMetrics");

                    b.Navigation("DeficitPhases");

                    b.Navigation("NeatLogs");

                    b.Navigation("Programs");

                    b.Navigation("RecoveryLogs");

                    b.Navigation("WeightLogs");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("TrainingApp.Core.Entities.Workout", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
